# Generated by Django 3.2.9 on 2021-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0002_auto_20211206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='portrait',
            field=models.CharField(default='Portrait1.png', max_length=64),
        ),
    ]
