# Generated by Django 3.2.9 on 2021-12-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0003_alter_dwarf_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
    ]
