# Generated by Django 3.2.9 on 2021-12-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0004_alter_dwarf_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='portrait',
            field=models.CharField(default='portrait1.png', max_length=64),
        ),
    ]
