# Generated by Django 3.2.9 on 2021-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0006_auto_20211207_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
