# Generated by Django 3.2.9 on 2021-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0007_user_gold_obtained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='Rate',
        ),
        migrations.AddField(
            model_name='mine',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
