# Generated by Django 3.2.9 on 2021-12-07 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0009_dwarf_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 12, 13, 18, 163307, tzinfo=utc)),
        ),
    ]
