# Generated by Django 3.2.9 on 2021-12-07 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0010_alter_dwarf_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dwarf',
            name='current_mine',
        ),
        migrations.RemoveField(
            model_name='dwarf',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 12, 7, 13, 8, 20, 878406, tzinfo=utc))),
                ('dwarf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwarf_jobs', to='dwarves.dwarf')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_jobs', to='dwarves.mine')),
            ],
        ),
    ]
