# Generated by Django 3.2.9 on 2021-12-08 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0012_alter_job_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 22, 34, 28, 922904, tzinfo=utc)),
        ),
    ]
