# Generated by Django 3.2.9 on 2021-12-08 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0013_alter_job_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 22, 45, 8, 647591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(choices=[('Gold', 'gold'), ('Iron', 'iron'), ('Marble', 'marble'), ('Quartz', 'quartz')], max_length=64),
        ),
    ]
