# Generated by Django 3.2.9 on 2021-12-08 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0014_auto_20211208_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 23, 39, 56, 270899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
