# Generated by Django 3.2.9 on 2021-12-01 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_highest_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='auctions.listing')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
